- name: add ssh key for penny
  authorized_key:
    user: penny
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMkzvczMQwys0GurvOWndfusl8nQSxBQUp+JTb/fze9/ Ansible"

- name: generate sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd
